### ISSUE TITLE
Cleans itself as soon as the application is opened

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#257] opened 2021-12-28 15:51 UTC
Good afternoon 

I have heard from some people I know who use Lte. That when they open the application and clean them, without giving to analyze or clean. Or without having activated the daily cleaning.

Leaving a notification of it with sound.

I upload the images they sent me:

https://ibb.co/WHb2KYj
https://ibb.co/3Fm5n4d
https://ibb.co/3MCLXZg

A hug and MERRY CHRISTMAS

Pd: The screenshots are from a Samsung, but it seems to happen in other mobiles.

Pd: app downloaded from github, fdroid or google play

Pd: Sorry for the late response on
https://github.com/TheRedSpy15/LTECleanerFOSS/discussions/243

**Comment by TheRedSpy15** [comment] 2022-01-29 08:43
Ok I have finally updated to android 12 on my personal device, and see this happening with my own eyes. Fix is know and will add it tomorrow

**Comment by TheRedSpy15** [comment] 2022-01-29 08:43
duplicate of #238

**Closed by TheRedSpy15** 2022-01-29 08:43 UTC
