### ISSUE TITLE
Application stuff

### ISSUE THREAD

**Issue by gallegonovato** [TheRedSpy15/LTECleanerFOSS#242] opened 2021-11-26 18:45 UTC
Good afternoon @TheRedSpy15

I originally thought of opening a topic as a bug. But I thought it better to do as a recoplit of things.

1----》On mobiles the lte app from github. In its main screen it says zero cleanup. But instead you get a notification that says cleaning for example 10 Mb.

2----》 in settings , applications, lte, notification. Two pop up. One that I do not know what. I upload screenshot: https://ibb.co/3hNbRWr . On the other hand in lineageos 18.1 or 17.1 does not come out.

3----》in Samsung terminals, Htc for example. You put in the lte settings. Dark mode or automatic. And it does not change to dark mode or black

4----》 keeps booting with the mobile. Even if you will never dial or use daily wipe.

5 ----》 people using the one from Google Play Store. They tell me that it says it contains ads. But he doesn't get any in the app.

6----》 in the list of files that clean lte. It says that I delete screenshots. But it does not delete them. Or for example cache of newpipe that also comes out and does not delete it. Or other applications. Or it doesn't delete recent ones.

7---》 happened twice and closed by itself. It didn't happen again.

8---》 On a Oneplus. It said that 4 Mb had to be cleared. And when I gave it to clean it put zero cleaned. It was solved by restarting the mobile

A hug and thank you for your time

**Comment by TheRedSpy15** [comment] 2021-11-26 22:02
1) this is because, when the notification is displayed, it doesn't show what is available to be cleaned. I shows what it just finished cleaning. So once you open the app, all the cleaning was already done. Not a bug

2) this is somewhat of a typo on my part, for got to rename it. best to leave it to its default. It's just permission for the background daily cleaner to notify you it did what it is supposed to do

3) did you try restarting the app afterwards? It doesn't take affect immediately (for now)

4) will be fixed soon.

5) This is true, it does display ads for playstore users. However, sometimes I experiment with the settings server side (no update required for users) which increase the amount of potential profit required for an ad to be displayed. Some times preventing any ads from being shown, if there isn't enough profit for me to even bother/annoy the user with

6) create a separate issue for this and I'll look into it

7) I'm currently rewriting the app with a new language. Once I finish doing so, I will have a much better crash reporting system, which should lead to a fix for this shortly after

8) refer to my response to the first question

**Closed** 2021-11-26 22:02 UTC
